version: '3'
services:
  app-starter:
    build:
        context: .
        dockerfile: Dockerfile.prod
    container_name: "lean-tech-challenge"
    image: lean-tech-challenge:latest
    env_file: ./.env.production
    ports:
      - ${PORT}:${PORT}