version: '3'
services:
  app-starter:
    build: .
    env_file: 
      - ./.env.development
    container_name: "lean-tech-challenge-dev"
    ports:
      - ${PORT}:${PORT}
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:3.6.0
    container_name: "mongo-lean-tech-challenge-dev"
    ports:
    - "27017:27017"
volumes:
  dbvolume: {}